FYAC_E = {}
FYAC_E.AntiNukeBlacklistedVehicles = { -- Yasaklı Araçlar
	{name = "cargoplane", ban = true , log = true},
	{name = "cerberus",   ban = true , log = true},
	{name = "cerberus2",  ban = true , log = true},
	{name = "cerberus3",  ban = true , log = true},
	{name = "hauler2",    ban = true , log = true},
	{name = "phantom2",   ban = true , log = true},
	{name = "terbyte",    ban = true , log = true},
	{name = "issi4",      ban = true , log = true},
	{name = "issi5",      ban = true , log = true},
	{name = "issi6",      ban = true , log = true},
	{name = "akula",      ban = true , log = true},
	{name = "annihilator",ban = true , log = true},
	{name = "buzzard",    ban = true ,log = true},
	{name = "hunter",     ban = true , log = true},
	{name = "savage",     ban = true , log = true},
	{name = "apc",        ban = true , log = true},
	{name = "barrage",    ban = true , log = true},
	{name = "chernobog",  ban = true , log = true},
	{name = "halftVCACk",  ban = true , log = true},
	{name = "khanjali",   ban = true , log = true},
	{name = "minitank",   ban = true , log = true},
	{name = "rhino",      ban = true ,log = true}, 
	{name = "scarab",     ban = true , log = true},
	{name = "dump",     ban = true , log = true},
	{name = "scarab2",    ban = true , log = true},
	{name = "scarab3",    ban = true , log = true},
	{name = "thruster",   ban = true , log = true},
	{name = "trailersmall2",ban = true , log = true},
	{name = "oppressor",  ban = true , log = true},
	{name = "oppressor2", ban = true , log = true},
	{name = "dominator4", ban = true , log = true},
	{name = "dominator5", ban = true , log = true},
	{name = "dominator6", ban = true , log = true},
	{name = "dukes2",     ban = true , log = true},
	{name = "impaler2",   ban = true , log = true},
	{name = "impaler3",   ban = true , log = true},
	{name = "impaler4",   ban = true , log = true},
	{name = "imperator",  ban = true , log = true},
	{name = "imperator2", ban = true , log = true},
	{name = "imperator3", ban = true , log = true},
	{name = "bruiser",    ban = true , log = true},
	{name = "bruiser2",   ban = true , log = true},
	{name = "bruiser3",   ban = true , log = true},
	{name = "brutus",     ban = true , log = true},
	{name = "brutus2",    ban = true , log = true},
	{name = "brutus3",    ban = true , log = true},
	{name = "caVCACara",   ban = true , log = true},
	{name = "dune4",      ban = true , log = true},
	{name = "dune5",      ban = true , log = true},
	{name = "insurgent",  ban = true , log = true},
	{name = "insurgent3", ban = true , log = true},
	{name = "menacer",    ban = true , log = true},
	{name = "nightshark", ban = true , log = true},
	{name = "technical",  ban = true , log = true},
	{name = "technical2", ban = true , log = true},
	{name = "technical3", ban = true , log = true},
	{name = "zhaba",      ban = true , log = true},
	{name = "avenger",    ban = true , log = true},
	{name = "avenger2",   ban = true , log = true},
	{name = "besra",      ban = false , log = false},
	-- {name = "blimp",      ban = false , log = true},
	-- {name = "blimp2",     ban = false , log = true},
	-- {name = "blimp3",     ban = false , log = true},
	{name = "jet",        ban = false , log = true},
	{name = "hydra",      ban = true , log = true},
	{name = "strikeforce",ban = true  , log = true},
	{name = "titan",      ban = false , log = true},
	{name = "volatol",    ban = true ,  log = true},
	{name = "limo2",      ban = true ,  log = true},
	{name = "zr380",      ban = true ,  log = true},
	{name = "zr3802",     ban = true ,  log = true},
	{name = "zr3803",     ban = true ,  log = true},
	{name = "deluxo",     ban = true ,  log = true},
	{name = "vigilante",  ban = true ,  log = true},
	{name = "boxville5",  ban = true ,  log = true},
	{name = "kuruma2",    ban = true ,  log = true},
	{name = "scramjet",   ban = true ,  log = true},
}

